const vnmenu = (prefix) => { 
return ` 
╭───「 *SOUND MENU* 」──
│
├➲ *${prefix}sound1*
├➲ *${prefix}sound2*
├➲ *${prefix}sound3*
├➲ *${prefix}sound4*
├➲ *${prefix}sound5*
├➲ *${prefix}sound6*
├➲ *${prefix}sound7*
├➲ *${prefix}sound8*
├➲ *${prefix}sound9*
├➲ *${prefix}sound10*
├➲ *${prefix}sound11*
├➲ *${prefix}sound12*
├➲ *${prefix}sound13*
├➲ *${prefix}sound14*
├➲ *${prefix}sound15*
├➲ *${prefix}sound16*
├➲ *${prefix}sound17*
├➲ *${prefix}sound18*
├➲ *${prefix}sound19*
├➲ *${prefix}sound20*
├➲ *${prefix}sound21*
├➲ *${prefix}sound22*
├➲ *${prefix}sound23*
├➲ *${prefix}sound24*
├➲ *${prefix}sound25*
├➲ *${prefix}sound26*
├➲ *${prefix}sound27*
├➲ *${prefix}sound28*
├➲ *${prefix}sound29*
├➲ *${prefix}sound30*
├➲ *${prefix}sound31*
├➲ *${prefix}sound32*
├➲ *${prefix}sound33*
├➲ *${prefix}sound34*
├➲ *${prefix}sound35*
├➲ *${prefix}sound36*
├➲ *${prefix}sound37*
├➲ *${prefix}sound38*
├➲ *${prefix}sound39*
├➲ *${prefix}sound40*
├➲ *${prefix}sound41*
├➲ *${prefix}sound42*
├➲ *${prefix}sound43*
├➲ *${prefix}sound44*
├➲ *${prefix}sound45*
├➲ *${prefix}sound46*
├➲ *${prefix}sound47*
├➲ *${prefix}sound48*
├➲ *${prefix}sound49*
├➲ *${prefix}sound50*
├➲ *${prefix}sound51*
├➲ *${prefix}sound52*
├➲ *${prefix}sound53*
├➲ *${prefix}sound54*
├➲ *${prefix}sound55*
├➲ *${prefix}sound56*
├➲ *${prefix}sound57*
├➲ *${prefix}sound58*
├➲ *${prefix}sound59*
├➲ *${prefix}sound60*
├➲ *${prefix}lagu1*
├➲ *${prefix}lagu2*
├➲ *${prefix}lagu3*
├➲ *${prefix}lagu4*
├➲ *${prefix}lagu5*
├➲ *${prefix}lagu6*
├➲ *${prefix}lagu7*
├➲ *${prefix}lagu8*
├➲ *${prefix}lemonkobasolo*
├➲ *${prefix}lovestory*
├➲ *${prefix}singoff*
├➲ *${prefix}singofftiktok*
├➲ *${prefix}bot*
├➲ *${prefix}iri*
├➲ *${prefix}dj1*
├➲ *${prefix}dj2*
├➲ *${prefix}pale*
├➲ *${prefix}baka*
├➲ *${prefix}bernyanyi*
├➲ *${prefix}yamate*
│
╰───────────────────`
	}
exports.vnmenu = vnmenu

